sys:
  sudo: /usr/local/bin/sudo

log:
  path: /var/log/cirrinad/cirrinad.log
  level: info

db:
  path: /var/db/cirrinad/cirrina.sqlite

disk:
  vm:
    path:
      image: /bhyve/disk
      state: /var/tmp/cirrinad/state/
      iso: /bhyve/isos
  default:
    size: 1G

vnc:
  ip: 0.0.0.0
  port: 6900

debug:
  ip: 0.0.0.0
  port: 2828

rom:
  path: /usr/local/share/uefi-firmware/BHYVE_UEFI.fd
  vars:
    template: /usr/local/share/uefi-firmware/BHYVE_UEFI_VARS.fd

network:
  grpc:
    ip: 0.0.0.0
    port: 50051
