sys:
  sudo: /usr/local/bin/sudo

log:
  path: /whatever/path/to/log/cirrinad.log
  level: info

db:
  path: /a/path/to/db/cirrina.sqlite

disk:
  vm:
    path:
      image: /some/path
      state: /some/other/path
      iso: /yet/another/path
  default:
    size: 1G

vnc:
  ip: 0.0.0.0
  port: 6900

rom:
  path: /usr/local/share/uefi-firmware/BHYVE_UEFI.fd
  vars:
    template: /usr/local/share/uefi-firmware/BHYVE_UEFI_VARS.fd

network:
  grpc:
    ip: 0.0.0.0
    port: 50051
