cirranad:
  stage: build
  tags:
    - FreeBSD
  script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.mouf.net/swills/go-supervisor.git
    - cd cirrinad
    - go build .
cirranactl:
  stage: build
  tags:
    - FreeBSD
  script:
    - cd cirrinactl
    - go build .
