stages:
  - build
  - test
  - upload
  - release

variables:
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}"
  VER: ${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}

qodana:
  when: manual
  tags:
    - k8s
  only:
    - main
    - merge_requests
  image:
    name: jetbrains/qodana-go:2023.3-eap
    entrypoint: [""]
  variables:
    QODANA_TOKEN: $qodana_token
  script:
    - export GOPROXY=http://10.0.1.152:3000
    - qodana --save-report --results-dir=$CI_PROJECT_DIR/.qodana
  artifacts:
    name: qodana-scan-results-"$CI_COMMIT_REF_NAME"
    paths:
      - $CI_PROJECT_DIR/.qodana
    expire_in: 1 week

cirranad:
  stage: build
  tags:
    - FreeBSD
  script:
    - export GOFLAGS="-trimpath"
    - git clone -b swillsv2 https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/swills/go-supervisor.git go-supervisor
    - cd cirrinad
    - export GOPROXY=http://10.0.1.152:3000
    - export GO_LDFLAGS="-X main.mainVersion=${VER} -s -w -extldflags -static -buildid=${CI_COMMIT_SHA}"
    - export GOOS=freebsd
    - export GOARCH=amd64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinad-${GOOS}-${GOARCH}-${VER} .
  artifacts:
    name: cirrinad-"$CI_COMMIT_REF_NAME"
    paths:
      - ./cirrinad/cirrinad-freebsd-amd64-${VER}
    expire_in: 1 week

cirranactl:
  stage: build
  tags:
    - FreeBSD
  script:
    - cd cirrinactl
    - export GOPROXY=http://10.0.1.152:3000
    - export CGO_ENABLED=0
    - export GO_LDFLAGS="-X cirrina/cirrinactl/cmd.mainVersion=${VER} -s -w -extldflags -static -buildid=${CI_COMMIT_SHA}"
    - export GOFLAGS="-trimpath"
    - export GOOS=freebsd
    - export GOARCH=amd64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${VER} .
    - export GOARCH=386
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${VER} .
    - export GOARCH=arm64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${VER} .
    - export GOOS=windows
    - export GOARCH=amd64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${VER}.exe .
    - export GOARCH=386
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${VER}.exe .
    - export GOARCH=arm64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${VER}.exe .
    - export GOOS=darwin
    - export GOARCH=amd64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${VER} .
    - export GOARCH=arm64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${VER} .
    - export GOOS=linux
    - export GOARCH=amd64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${VER} .
    - export GOARCH=386
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${VER} .
    - export GOARCH=arm64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${VER} .
  artifacts:
    name: cirrinactl-"$CI_COMMIT_REF_NAME"
    paths:
      - ./cirrinactl/cirrinactl-freebsd-amd64-${VER}
      - ./cirrinactl/cirrinactl-freebsd-386-${VER}
      - ./cirrinactl/cirrinactl-freebsd-arm64-${VER}
      - ./cirrinactl/cirrinactl-windows-amd64-${VER}.exe
      - ./cirrinactl/cirrinactl-windows-386-${VER}.exe
      - ./cirrinactl/cirrinactl-windows-arm64-${VER}.exe
      - ./cirrinactl/cirrinactl-darwin-amd64-${VER}
      - ./cirrinactl/cirrinactl-darwin-arm64-${VER}
      - ./cirrinactl/cirrinactl-linux-amd64-${VER}
      - ./cirrinactl/cirrinactl-linux-386-${VER}
      - ./cirrinactl/cirrinactl-linux-arm64-${VER}
    expire_in: 1 week

cirrinad-upload:
  stage: upload
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      curl -s --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file cirrinad/cirrinad-freebsd-amd64-${VER} "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinad-freebsd-amd64"
    - echo

cirrinactl-upload:
  stage: upload
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - export GOOS=freebsd
    - export GOARCH=amd64
    - |
      curl -s --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file cirrinactl/cirrinactl-${GOOS}-${GOARCH}-${VER} "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-${GOOS}-${GOARCH}"
    - export GOARCH=386
    - |
      curl -s --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file cirrinactl/cirrinactl-${GOOS}-${GOARCH}-${VER} "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-${GOOS}-${GOARCH}"
    - export GOARCH=arm64
    - |
      curl -s --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file cirrinactl/cirrinactl-${GOOS}-${GOARCH}-${VER} "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-${GOOS}-${GOARCH}"
    - export GOOS=windows
    - export GOARCH=amd64
    - |
      curl -s --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file cirrinactl/cirrinactl-${GOOS}-${GOARCH}-${VER}.exe "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-${GOOS}-${GOARCH}.exe"
    - export GOARCH=386
    - |
      curl -s --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file cirrinactl/cirrinactl-${GOOS}-${GOARCH}-${VER}.exe "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-${GOOS}-${GOARCH}.exe"
    - export GOARCH=arm64
    - |
      curl -s --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file cirrinactl/cirrinactl-${GOOS}-${GOARCH}-${VER}.exe "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-${GOOS}-${GOARCH}.exe"
    - export GOOS=darwin
    - export GOARCH=amd64
    - |
      curl -s --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file cirrinactl/cirrinactl-${GOOS}-${GOARCH}-${VER} "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-${GOOS}-${GOARCH}"
    - export GOARCH=arm64
    - |
      curl -s --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file cirrinactl/cirrinactl-${GOOS}-${GOARCH}-${VER} "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-${GOOS}-${GOARCH}"
    - export GOOS=linux
    - export GOARCH=amd64
    - |
      curl -s --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file cirrinactl/cirrinactl-${GOOS}-${GOARCH}-${VER} "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-${GOOS}-${GOARCH}"
    - export GOARCH=386
    - |
      curl -s --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file cirrinactl/cirrinactl-${GOOS}-${GOARCH}-${VER} "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-${GOOS}-${GOARCH}"
    - export GOARCH=arm64
    - |
      curl -s --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file cirrinactl/cirrinactl-${GOOS}-${GOARCH}-${VER} "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-${GOOS}-${GOARCH}"
    - echo

release:
  stage: release
  tags:
    - FreeBSD
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      release-cli create --name "Release $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG \
        --assets-link "{\"name\":\"cirrinad-freebsd-amd64\",\"url\":\"${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinad-freebsd-amd64\"}" \
        --assets-link "{\"name\":\"cirrinactl-freebsd-amd64\",\"url\":\"${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-freebsd-amd64\"}" \
        --assets-link "{\"name\":\"cirrinactl-freebsd-i386\",\"url\":\"${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-freebsd-i386\"}" \
        --assets-link "{\"name\":\"cirrinactl-freebsd-arm64\",\"url\":\"${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-freebsd-arm64\"}" \
        --assets-link "{\"name\":\"cirrinactl-windows-amd64.exe\",\"url\":\"${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-windows-amd64.exe\"}" \
        --assets-link "{\"name\":\"cirrinactl-windows-i386.exe\",\"url\":\"${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-windows-i386.exe\"}" \
        --assets-link "{\"name\":\"cirrinactl-windows-arm64.exe\",\"url\":\"${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-windows-arm64.exe\"}" \
        --assets-link "{\"name\":\"cirrinactl-darwin-amd64\",\"url\":\"${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-darwin-amd64\"}" \
        --assets-link "{\"name\":\"cirrinactl-darwin-arm64\",\"url\":\"${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-darwin-arm64\"}" \
        --assets-link "{\"name\":\"cirrinactl-linux-amd64\",\"url\":\"${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-linux-amd64\"}" \
        --assets-link "{\"name\":\"cirrinactl-linux-i386\",\"url\":\"${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-linux-i386\"}" \
        --assets-link "{\"name\":\"cirrinactl-linux-arm64\",\"url\":\"${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-linux-arm64\"}"
    - echo
