
cirranad:
  stage: build
  tags:
    - FreeBSD
  script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.mouf.net/swills/go-supervisor.git go-supervisor
    - cd cirrinad
    - go build .
  artifacts:
    name: cirrinad-"$CI_COMMIT_REF_NAME"
    paths:
      - ./cirrinad/cirrinad

cirranactl:
  stage: build
  tags:
    - FreeBSD
  script:
    - cd cirrinactl
    - export CGO_ENABLED=0
    - export GO_LDFLAGS="-s -w -extldflags -static"
    - export GOOS=freebsd
    - export GOARCH=amd64
    - go build -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH} .
    - export GOARCH=386
    - go build -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH} .
    - export GOARCH=arm64
    - go build -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH} .
    - export GOOS=windows
    - export GOARCH=amd64
    - go build -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH} .
    - export GOARCH=386
    - go build -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH} .
    - export GOARCH=arm64
    - go build -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH} .
  artifacts:
    name: cirrinactl-"$CI_COMMIT_REF_NAME"
    paths:
      - ./cirrinactl/cirrinactl-freebsd-amd64
      - ./cirrinactl/cirrinactl-freebsd-386
      - ./cirrinactl/cirrinactl-freebsd-arm64
      - ./cirrinactl/cirrinactl-windows-amd64
      - ./cirrinactl/cirrinactl-windows-386
      - ./cirrinactl/cirrinactl-windows-arm64
