stages:
  - build
  - test
  - upload

qodana:
  when: manual
  tags:
    - k8s
  only:
    - main
    - merge_requests
  image:
    name: jetbrains/qodana-go:2023.3-eap
    entrypoint: [""]
  variables:
    QODANA_TOKEN: $qodana_token
  script:
    - export GOPROXY=http://10.0.1.152:3000
    - qodana --save-report --results-dir=$CI_PROJECT_DIR/.qodana
  artifacts:
    name: qodana-scan-results-"$CI_COMMIT_REF_NAME"
    paths:
      - $CI_PROJECT_DIR/.qodana

cirranad:
  stage: build
  tags:
    - FreeBSD
  variables:
    VER: ${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}
  script:
    - echo VER is ${VER}
    - export GOFLAGS="-trimpath"
    - git clone -b swillsv2 https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/swills/go-supervisor.git go-supervisor
    - cd cirrinad
    - export GOPROXY=http://10.0.1.152:3000
    - export GO_LDFLAGS="-X main.mainVersion=${VER} -s -w -extldflags -static -buildid=${CI_COMMIT_SHA}"
    - export GOOS=freebsd
    - export GOARCH=amd64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinad-${GOOS}-${GOARCH}-${VER} .
  artifacts:
    name: cirrinad-"$CI_COMMIT_REF_NAME"
    paths:
      - ./cirrinad/cirrinad-freebsd-amd64-${VER}

cirranactl:
  stage: build
  tags:
    - FreeBSD
  variables:
    VER: ${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}
  script:
    - echo VER is ${VER}
    - cd cirrinactl
    - export GOPROXY=http://10.0.1.152:3000
    - export CGO_ENABLED=0
    - export GO_LDFLAGS="-X cirrina/cirrinactl/cmd.mainVersion=${VER} -s -w -extldflags -static -buildid=${CI_COMMIT_SHA}"
    - export GOFLAGS="-trimpath"
    - export GOOS=freebsd
    - export GOARCH=amd64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${VER} .
    - export GOARCH=386
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${VER} .
    - export GOARCH=arm64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${VER} .
    - export GOOS=windows
    - export GOARCH=amd64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${VER}.exe .
    - export GOARCH=386
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${VER}.exe .
    - export GOARCH=arm64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${VER}.exe .
    - export GOOS=darwin
    - export GOARCH=amd64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${VER} .
    - export GOARCH=arm64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${VER} .
    - export GOOS=linux
    - export GOARCH=amd64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${VER} .
    - export GOARCH=386
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${VER} .
    - export GOARCH=arm64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${VER} .
  artifacts:
    name: cirrinactl-"$CI_COMMIT_REF_NAME"
    paths:
      - ./cirrinactl/cirrinactl-freebsd-amd64-${VER}
      - ./cirrinactl/cirrinactl-freebsd-386-${VER}
      - ./cirrinactl/cirrinactl-freebsd-arm64-${VER}
      - ./cirrinactl/cirrinactl-windows-amd64-${VER}.exe
      - ./cirrinactl/cirrinactl-windows-386-${VER}.exe
      - ./cirrinactl/cirrinactl-windows-arm64-${VER}.exe
      - ./cirrinactl/cirrinactl-darwin-amd64-${VER}
      - ./cirrinactl/cirrinactl-darwin-arm64-${VER}
      - ./cirrinactl/cirrinactl-linux-amd64-${VER}
      - ./cirrinactl/cirrinactl-linux-386-${VER}
      - ./cirrinactl/cirrinactl-linux-arm64-${VER}

cirrinad-upload:
  stage: upload
  rules:
    - if: $CI_COMMIT_TAG
  variables:
    VER: ${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}
  script:
    - echo VER is ${VER}
    - |
      curl -s --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file cirrinad/cirrinad-freebsd-amd64-${VER} "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_COMMIT_TAG}/cirrinad-freebsd-amd64?select=package_file"

cirrinactl-upload:
  stage: upload
  rules:
    - if: $CI_COMMIT_TAG
  variables:
    VER: ${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}
  script:
    - echo VER is ${VER}
    - export GOOS=freebsd
    - export GOARCH=amd64
    - env | sort
    - |
      curl -s --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file cirrinactl/cirrinactl-${GOOS}-${GOARCH}-${VER} "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_COMMIT_TAG}/cirrinactl-${GOOS}-${GOARCH}?select=package_file"

