qodana:
  when: manual
  tags:
    - k8s
  only:
    - main
    - merge_requests
  image:
    name: jetbrains/qodana-go:2023.3-eap
    entrypoint: [""]
  variables:
    QODANA_TOKEN: $qodana_token
  script:
    - qodana --save-report --results-dir=$CI_PROJECT_DIR/.qodana
  artifacts:
    name: qodana-scan-results-"$CI_COMMIT_REF_NAME"
    paths:
      - $CI_PROJECT_DIR/.qodana

cirranad:
  stage: build
  tags:
    - FreeBSD
  script:
    - VER=$(git rev-parse --short HEAD)
    - export GOFLAGS="-trimpath"
    - git clone -b swillsv2 https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/swills/go-supervisor.git go-supervisor
    - cd cirrinad
    - export GO_LDFLAGS="-X main.mainVersion=${VER} -s -w -extldflags -static -buildid=${CI_COMMIT_SHA}"
    - export GOOS=freebsd
    - export GOARCH=amd64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinad-${GOOS}-${GOARCH}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA} .
  artifacts:
    name: cirrinad-"$CI_COMMIT_REF_NAME"
    paths:
      - ./cirrinad/cirrinad-freebsd-amd64-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}

cirranactl:
  stage: build
  tags:
    - FreeBSD
  script:
    - VER=$(git rev-parse --short HEAD)
    - cd cirrinactl
    - export CGO_ENABLED=0
    - export GO_LDFLAGS="-X cirrina/cirrinactl/cmd.mainVersion=${VER} -s -w -extldflags -static -buildid=${CI_COMMIT_SHA}"
    - export GOFLAGS="-trimpath"
    - export GOOS=freebsd
    - export GOARCH=amd64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA} .
    - export GOARCH=386
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA} .
    - export GOARCH=arm64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA} .
    - export GOOS=windows
    - export GOARCH=amd64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}.exe .
    - export GOARCH=386
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}.exe .
    - export GOARCH=arm64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}.exe .
    - export GOOS=darwin
    - export GOARCH=amd64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA} .
    - export GOARCH=arm64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA} .
    - export GOOS=linux
    - export GOARCH=amd64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA} .
    - export GOARCH=386
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA} .
    - export GOARCH=arm64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA} .
  artifacts:
    name: cirrinactl-"$CI_COMMIT_REF_NAME"
    paths:
      - ./cirrinactl/cirrinactl-freebsd-amd64-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}
      - ./cirrinactl/cirrinactl-freebsd-386-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}
      - ./cirrinactl/cirrinactl-freebsd-arm64-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}
      - ./cirrinactl/cirrinactl-windows-amd64-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}.exe
      - ./cirrinactl/cirrinactl-windows-386-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}.exe
      - ./cirrinactl/cirrinactl-windows-arm64-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}.exe
      - ./cirrinactl/cirrinactl-darwin-amd64-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}
      - ./cirrinactl/cirrinactl-darwin-arm64-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}
      - ./cirrinactl/cirrinactl-linux-amd64-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}
      - ./cirrinactl/cirrinactl-linux-386-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}
      - ./cirrinactl/cirrinactl-linux-arm64-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}
