
cirranad:
  stage: build
  tags:
    - FreeBSD
  script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.mouf.net/swills/go-supervisor.git go-supervisor
    - cd cirrinad
    - go build .
    - export GO_LDFLAGS="-s -w -extldflags -static"
    - export GOOS=freebsd
    - export GOARCH=amd64
    - go build -ldflags="${GO_LDFLAGS}" -o cirrinad-${GOOS}-${GOARCH}-${CI_BUILD_REF_SLUG}-${CI_COMMIT_SHORT_SHA} .
  artifacts:
    name: cirrinad-"$CI_COMMIT_REF_NAME"
    paths:
      - ./cirrinad/cirrinad-${GOOS}-${GOARCH}-${CI_BUILD_REF_SLUG}-${CI_COMMIT_SHORT_SHA}

cirranactl:
  stage: build
  tags:
    - FreeBSD
  script:
    - cd cirrinactl
    - export CGO_ENABLED=0
    - export GO_LDFLAGS="-s -w -extldflags -static"
    - export GOOS=freebsd
    - export GOARCH=amd64
    - go build -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${CI_BUILD_REF_SLUG}-${CI_COMMIT_SHORT_SHA} .
    - export GOARCH=386
    - go build -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${CI_BUILD_REF_SLUG}-${CI_COMMIT_SHORT_SHA} .
    - export GOARCH=arm64
    - go build -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${CI_BUILD_REF_SLUG}-${CI_COMMIT_SHORT_SHA} .
    - export GOOS=windows
    - export GOARCH=amd64
    - go build -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${CI_BUILD_REF_SLUG}-${CI_COMMIT_SHORT_SHA} .
    - export GOARCH=386
    - go build -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${CI_BUILD_REF_SLUG}-${CI_COMMIT_SHORT_SHA} .
    - export GOARCH=arm64
    - go build -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${CI_BUILD_REF_SLUG}-${CI_COMMIT_SHORT_SHA} .
    - export GOOS=darwin
    - export GOARCH=amd64
    - go build -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${CI_BUILD_REF_SLUG}-${CI_COMMIT_SHORT_SHA} .
    - export GOARCH=arm64
    - go build -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${CI_BUILD_REF_SLUG}-${CI_COMMIT_SHORT_SHA} .
    - export GOOS=linux
    - export GOARCH=amd64
    - go build -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${CI_BUILD_REF_SLUG}-${CI_COMMIT_SHORT_SHA} .
    - export GOARCH=386
    - go build -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${CI_BUILD_REF_SLUG}-${CI_COMMIT_SHORT_SHA} .
    - export GOARCH=arm64
    - go build -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${CI_BUILD_REF_SLUG}-${CI_COMMIT_SHORT_SHA} .
  artifacts:
    name: cirrinactl-"$CI_COMMIT_REF_NAME"
    paths:
      - ./cirrinactl/cirrinactl-freebsd-amd64-${CI_BUILD_REF_SLUG}-${CI_COMMIT_SHORT_SHA}
      - ./cirrinactl/cirrinactl-freebsd-386-${CI_BUILD_REF_SLUG}-${CI_COMMIT_SHORT_SHA}
      - ./cirrinactl/cirrinactl-freebsd-arm64-${CI_BUILD_REF_SLUG}-${CI_COMMIT_SHORT_SHA}
      - ./cirrinactl/cirrinactl-windows-amd64-${CI_BUILD_REF_SLUG}-${CI_COMMIT_SHORT_SHA}
      - ./cirrinactl/cirrinactl-windows-386-${CI_BUILD_REF_SLUG}-${CI_COMMIT_SHORT_SHA}
      - ./cirrinactl/cirrinactl-windows-arm64-${CI_BUILD_REF_SLUG}-${CI_COMMIT_SHORT_SHA}
      - ./cirrinactl/cirrinactl-darwin-amd64-${CI_BUILD_REF_SLUG}-${CI_COMMIT_SHORT_SHA}
      - ./cirrinactl/cirrinactl-darwin-arm64-${CI_BUILD_REF_SLUG}-${CI_COMMIT_SHORT_SHA}
      - ./cirrinactl/cirrinactl-linux-amd64-${CI_BUILD_REF_SLUG}-${CI_COMMIT_SHORT_SHA}
      - ./cirrinactl/cirrinactl-linux-386-${CI_BUILD_REF_SLUG}-${CI_COMMIT_SHORT_SHA}
      - ./cirrinactl/cirrinactl-linux-arm64-${CI_BUILD_REF_SLUG}-${CI_COMMIT_SHORT_SHA}
