stages:
  - build
  - test
  - upload
  - release

variables:
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}"
  VER: ${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}
  GOTOOLCHAIN: local

gen-check:
  stage: build
  needs: []
  tags:
    - FreeBSD
  script:
    - export GOFLAGS="-trimpath"
    - git clone -b swillsv2 https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/swills/go-supervisor.git go-supervisor
    - cd cirrinad
    - export GOPROXY=https://athens.mouf.io
    - export GOOS=freebsd
    - export GOARCH=amd64
    - go generate ./...
    - DIFF_WC=`git diff | wc -l | xargs` ; if [ ${DIFF_WC} -ne 0 ]; then echo 'generated code differs from committed code' ; git diff --stat ; exit 1 ; fi

cirrinad:
  stage: build
  needs: []
  tags:
    - FreeBSD
  script:
    - export GOFLAGS="-trimpath"
    - git clone -b swillsv2 https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/swills/go-supervisor.git go-supervisor
    - cd cirrinad
    - export GOPROXY=https://athens.mouf.io
    - export GO_LDFLAGS="-X main.mainVersion=${VER} -s -w -extldflags -static -buildid=${CI_COMMIT_SHA}"
    - export GOOS=freebsd
    - export GOARCH=amd64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinad-${GOOS}-${GOARCH}-${VER} .
  artifacts:
    name: cirrinad-"$CI_COMMIT_REF_NAME"
    paths:
      - ./cirrinad/cirrinad-freebsd-amd64-${VER}
    expire_in: 1 week

cirrinactl:
  stage: build
  needs: []
  tags:
    - FreeBSD
  script:
    - cd cirrinactl
    - export GOPROXY=https://athens.mouf.io
    - export CGO_ENABLED=0
    - export GO_LDFLAGS="-X cirrina/cirrinactl/cmd.mainVersion=${VER} -s -w -extldflags -static -buildid=${CI_COMMIT_SHA}"
    - export GOFLAGS="-trimpath"
    - export GOOS=freebsd
    - export GOARCH=amd64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${VER} .
    - export GOARCH=386
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${VER} .
    - export GOARCH=arm64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${VER} .
    - export GOARCH=riscv64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${VER} .
    - export GOOS=windows
    - export GOARCH=amd64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${VER}.exe .
    - export GOARCH=386
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${VER}.exe .
    - export GOARCH=arm64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${VER}.exe .
    - export GOOS=darwin
    - export GOARCH=amd64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${VER} .
    - export GOARCH=arm64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${VER} .
    - export GOOS=linux
    - export GOARCH=amd64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${VER} .
    - export GOARCH=386
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${VER} .
    - export GOARCH=arm64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinactl-${GOOS}-${GOARCH}-${VER} .
  artifacts:
    name: cirrinactl-"$CI_COMMIT_REF_NAME"
    paths:
      - ./cirrinactl/cirrinactl-freebsd-amd64-${VER}
      - ./cirrinactl/cirrinactl-freebsd-386-${VER}
      - ./cirrinactl/cirrinactl-freebsd-arm64-${VER}
      - ./cirrinactl/cirrinactl-freebsd-riscv64-${VER}
      - ./cirrinactl/cirrinactl-windows-amd64-${VER}.exe
      - ./cirrinactl/cirrinactl-windows-386-${VER}.exe
      - ./cirrinactl/cirrinactl-windows-arm64-${VER}.exe
      - ./cirrinactl/cirrinactl-darwin-amd64-${VER}
      - ./cirrinactl/cirrinactl-darwin-arm64-${VER}
      - ./cirrinactl/cirrinactl-linux-amd64-${VER}
      - ./cirrinactl/cirrinactl-linux-386-${VER}
      - ./cirrinactl/cirrinactl-linux-arm64-${VER}
    expire_in: 1 week

cirrinaweb:
  stage: build
  needs: []
  tags:
    - FreeBSD
  script:
    - cd cirrinaweb
    - export GOPROXY=https://athens.mouf.io
    - export CGO_ENABLED=0
    - export GO_LDFLAGS="-X cirrina/cirrinaweb/cmd.mainVersion=${VER} -s -w -extldflags -static -buildid=${CI_COMMIT_SHA}"
    - export GOFLAGS="-trimpath"
    - export GOOS=freebsd
    - export GOARCH=amd64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinaweb-${GOOS}-${GOARCH}-${VER} .
    - export GOARCH=386
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinaweb-${GOOS}-${GOARCH}-${VER} .
    - export GOARCH=arm64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinaweb-${GOOS}-${GOARCH}-${VER} .
    - export GOARCH=riscv64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinaweb-${GOOS}-${GOARCH}-${VER} .
    - export GOOS=windows
    - export GOARCH=amd64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinaweb-${GOOS}-${GOARCH}-${VER}.exe .
    - export GOARCH=386
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinaweb-${GOOS}-${GOARCH}-${VER}.exe .
    - export GOARCH=arm64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinaweb-${GOOS}-${GOARCH}-${VER}.exe .
    - export GOOS=darwin
    - export GOARCH=amd64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinaweb-${GOOS}-${GOARCH}-${VER} .
    - export GOARCH=arm64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinaweb-${GOOS}-${GOARCH}-${VER} .
    - export GOOS=linux
    - export GOARCH=amd64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinaweb-${GOOS}-${GOARCH}-${VER} .
    - export GOARCH=386
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinaweb-${GOOS}-${GOARCH}-${VER} .
    - export GOARCH=arm64
    - go build "${GOFLAGS}" -ldflags="${GO_LDFLAGS}" -o cirrinaweb-${GOOS}-${GOARCH}-${VER} .
  artifacts:
    name: cirrinaweb-"$CI_COMMIT_REF_NAME"
    paths:
      - ./cirrinaweb/cirrinaweb-freebsd-amd64-${VER}
      - ./cirrinaweb/cirrinaweb-freebsd-386-${VER}
      - ./cirrinaweb/cirrinaweb-freebsd-arm64-${VER}
      - ./cirrinaweb/cirrinaweb-freebsd-riscv64-${VER}
      - ./cirrinaweb/cirrinaweb-windows-amd64-${VER}.exe
      - ./cirrinaweb/cirrinaweb-windows-386-${VER}.exe
      - ./cirrinaweb/cirrinaweb-windows-arm64-${VER}.exe
      - ./cirrinaweb/cirrinaweb-darwin-amd64-${VER}
      - ./cirrinaweb/cirrinaweb-darwin-arm64-${VER}
      - ./cirrinaweb/cirrinaweb-linux-amd64-${VER}
      - ./cirrinaweb/cirrinaweb-linux-386-${VER}
      - ./cirrinaweb/cirrinaweb-linux-arm64-${VER}
    expire_in: 1 week

lint:
  stage: test
  needs: []
  tags:
    - FreeBSD
  script:
    - go fmt $(go list ./...) | diff -u /dev/null -
    - go vet $(go list ./...)
    - export GOBIN=${HOME}/bin
    - export PATH=${GOBIN}:${PATH}
    - go mod tidy -v
    - go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.7
    - golangci-lint run ./...
    - go install go.uber.org/mock/mockgen@v0.5.0
    - go generate ./...
    - git diff | diff -u /dev/null -

go-test:
  stage: test
  needs: []
  tags:
    - FreeBSD
  script:
    - export GOBIN=${HOME}/bin
    - export PATH=${GOBIN}:${PATH}
    - go test -shuffle=on -v ./... -coverpkg=./... -coverprofile=coverage.txt -covermode count -tags test
    - go tool cover -func coverage.txt
    - go tool cover -html coverage.txt -o cover.html
    - go install gotest.tools/gotestsum@v1.12.0
    - gotestsum --junitfile report.xml --format testname
    - go install github.com/boumenot/gocover-cobertura@v1.3.0
    - gocover-cobertura < coverage.txt > coverage.xml
    - go test -race ./cirrinad
  coverage: '/^total:\s+\(statements\)\s+(\d+\.\d+)%$/'
  artifacts:
    when: always
    name: coverage
    paths:
      - cover.html
    expire_in: 1 week
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

cirrinad-upload:
  stage: upload
  rules:
    - if: $CI_COMMIT_TAG
  dependencies:
    - cirrinad
  script:
    - |
      curl -s --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file cirrinad/cirrinad-freebsd-amd64-${VER} "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinad-freebsd-amd64"
    - echo

cirrinactl-upload:
  stage: upload
  rules:
    - if: $CI_COMMIT_TAG
  dependencies:
    - cirrinactl
  script:
    - export GOOS=freebsd
    - export GOARCH=amd64
    - |
      curl -s --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file cirrinactl/cirrinactl-${GOOS}-${GOARCH}-${VER} "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-${GOOS}-${GOARCH}"
    - export GOARCH=386
    - |
      curl -s --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file cirrinactl/cirrinactl-${GOOS}-${GOARCH}-${VER} "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-${GOOS}-${GOARCH}"
    - export GOARCH=arm64
    - |
      curl -s --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file cirrinactl/cirrinactl-${GOOS}-${GOARCH}-${VER} "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-${GOOS}-${GOARCH}"
    - export GOARCH=riscv64
    - |
      curl -s --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file cirrinactl/cirrinactl-${GOOS}-${GOARCH}-${VER} "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-${GOOS}-${GOARCH}"
    - export GOOS=windows
    - export GOARCH=amd64
    - |
      curl -s --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file cirrinactl/cirrinactl-${GOOS}-${GOARCH}-${VER}.exe "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-${GOOS}-${GOARCH}.exe"
    - export GOARCH=386
    - |
      curl -s --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file cirrinactl/cirrinactl-${GOOS}-${GOARCH}-${VER}.exe "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-${GOOS}-${GOARCH}.exe"
    - export GOARCH=arm64
    - |
      curl -s --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file cirrinactl/cirrinactl-${GOOS}-${GOARCH}-${VER}.exe "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-${GOOS}-${GOARCH}.exe"
    - export GOOS=darwin
    - export GOARCH=amd64
    - |
      curl -s --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file cirrinactl/cirrinactl-${GOOS}-${GOARCH}-${VER} "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-${GOOS}-${GOARCH}"
    - export GOARCH=arm64
    - |
      curl -s --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file cirrinactl/cirrinactl-${GOOS}-${GOARCH}-${VER} "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-${GOOS}-${GOARCH}"
    - export GOOS=linux
    - export GOARCH=amd64
    - |
      curl -s --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file cirrinactl/cirrinactl-${GOOS}-${GOARCH}-${VER} "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-${GOOS}-${GOARCH}"
    - export GOARCH=386
    - |
      curl -s --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file cirrinactl/cirrinactl-${GOOS}-${GOARCH}-${VER} "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-${GOOS}-${GOARCH}"
    - export GOARCH=arm64
    - |
      curl -s --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file cirrinactl/cirrinactl-${GOOS}-${GOARCH}-${VER} "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-${GOOS}-${GOARCH}"
    - echo

cirrinaweb-upload:
  stage: upload
  rules:
    - if: $CI_COMMIT_TAG
  dependencies:
    - cirrinaweb
  script:
    - export GOOS=freebsd
    - export GOARCH=amd64
    - |
      curl -s --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file cirrinaweb/cirrinaweb-${GOOS}-${GOARCH}-${VER} "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinaweb-${GOOS}-${GOARCH}"
    - export GOARCH=386
    - |
      curl -s --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file cirrinaweb/cirrinaweb-${GOOS}-${GOARCH}-${VER} "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinaweb-${GOOS}-${GOARCH}"
    - export GOARCH=arm64
    - |
      curl -s --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file cirrinaweb/cirrinaweb-${GOOS}-${GOARCH}-${VER} "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinaweb-${GOOS}-${GOARCH}"
    - export GOARCH=riscv64
    - |
      curl -s --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file cirrinaweb/cirrinaweb-${GOOS}-${GOARCH}-${VER} "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinaweb-${GOOS}-${GOARCH}"
    - export GOOS=windows
    - export GOARCH=amd64
    - |
      curl -s --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file cirrinaweb/cirrinaweb-${GOOS}-${GOARCH}-${VER}.exe "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinaweb-${GOOS}-${GOARCH}.exe"
    - export GOARCH=386
    - |
      curl -s --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file cirrinaweb/cirrinaweb-${GOOS}-${GOARCH}-${VER}.exe "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinaweb-${GOOS}-${GOARCH}.exe"
    - export GOARCH=arm64
    - |
      curl -s --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file cirrinaweb/cirrinaweb-${GOOS}-${GOARCH}-${VER}.exe "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinaweb-${GOOS}-${GOARCH}.exe"
    - export GOOS=darwin
    - export GOARCH=amd64
    - |
      curl -s --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file cirrinaweb/cirrinaweb-${GOOS}-${GOARCH}-${VER} "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinaweb-${GOOS}-${GOARCH}"
    - export GOARCH=arm64
    - |
      curl -s --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file cirrinaweb/cirrinaweb-${GOOS}-${GOARCH}-${VER} "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinaweb-${GOOS}-${GOARCH}"
    - export GOOS=linux
    - export GOARCH=amd64
    - |
      curl -s --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file cirrinaweb/cirrinaweb-${GOOS}-${GOARCH}-${VER} "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinaweb-${GOOS}-${GOARCH}"
    - export GOARCH=386
    - |
      curl -s --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file cirrinaweb/cirrinaweb-${GOOS}-${GOARCH}-${VER} "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinaweb-${GOOS}-${GOARCH}"
    - export GOARCH=arm64
    - |
      curl -s --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file cirrinaweb/cirrinaweb-${GOOS}-${GOARCH}-${VER} "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinaweb-${GOOS}-${GOARCH}"
    - echo

release:
  stage: release
  tags:
    - FreeBSD
  rules:
    - if: $CI_COMMIT_TAG
  dependencies:
    - cirrinad-upload
    - cirrinactl-upload
  script:
    - |
      release-cli create --name "Release $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG \
        --assets-link "{\"name\":\"cirrinad-freebsd-amd64\",\"url\":\"${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinad-freebsd-amd64\"}" \
        --assets-link "{\"name\":\"cirrinactl-freebsd-amd64\",\"url\":\"${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-freebsd-amd64\"}" \
        --assets-link "{\"name\":\"cirrinactl-freebsd-i386\",\"url\":\"${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-freebsd-i386\"}" \
        --assets-link "{\"name\":\"cirrinactl-freebsd-arm64\",\"url\":\"${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-freebsd-arm64\"}" \
        --assets-link "{\"name\":\"cirrinactl-freebsd-riscv64\",\"url\":\"${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-freebsd-riscv64\"}" \
        --assets-link "{\"name\":\"cirrinactl-windows-amd64.exe\",\"url\":\"${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-windows-amd64.exe\"}" \
        --assets-link "{\"name\":\"cirrinactl-windows-i386.exe\",\"url\":\"${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-windows-i386.exe\"}" \
        --assets-link "{\"name\":\"cirrinactl-windows-arm64.exe\",\"url\":\"${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-windows-arm64.exe\"}" \
        --assets-link "{\"name\":\"cirrinactl-darwin-amd64\",\"url\":\"${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-darwin-amd64\"}" \
        --assets-link "{\"name\":\"cirrinactl-darwin-arm64\",\"url\":\"${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-darwin-arm64\"}" \
        --assets-link "{\"name\":\"cirrinactl-linux-amd64\",\"url\":\"${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-linux-amd64\"}" \
        --assets-link "{\"name\":\"cirrinactl-linux-i386\",\"url\":\"${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-linux-i386\"}" \
        --assets-link "{\"name\":\"cirrinactl-linux-arm64\",\"url\":\"${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinactl-linux-arm64\"}" \
        --assets-link "{\"name\":\"cirrinaweb-freebsd-amd64\",\"url\":\"${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinaweb-freebsd-amd64\"}" \
        --assets-link "{\"name\":\"cirrinaweb-freebsd-i386\",\"url\":\"${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinaweb-freebsd-i386\"}" \
        --assets-link "{\"name\":\"cirrinaweb-freebsd-arm64\",\"url\":\"${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinaweb-freebsd-arm64\"}" \
        --assets-link "{\"name\":\"cirrinaweb-freebsd-riscv64\",\"url\":\"${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinaweb-freebsd-riscv64\"}" \
        --assets-link "{\"name\":\"cirrinaweb-windows-amd64.exe\",\"url\":\"${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinaweb-windows-amd64.exe\"}" \
        --assets-link "{\"name\":\"cirrinaweb-windows-i386.exe\",\"url\":\"${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinaweb-windows-i386.exe\"}" \
        --assets-link "{\"name\":\"cirrinaweb-windows-arm64.exe\",\"url\":\"${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinaweb-windows-arm64.exe\"}" \
        --assets-link "{\"name\":\"cirrinaweb-darwin-amd64\",\"url\":\"${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinaweb-darwin-amd64\"}" \
        --assets-link "{\"name\":\"cirrinaweb-darwin-arm64\",\"url\":\"${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinaweb-darwin-arm64\"}" \
        --assets-link "{\"name\":\"cirrinaweb-linux-amd64\",\"url\":\"${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinaweb-linux-amd64\"}" \
        --assets-link "{\"name\":\"cirrinaweb-linux-i386\",\"url\":\"${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinaweb-linux-i386\"}" \
        --assets-link "{\"name\":\"cirrinaweb-linux-arm64\",\"url\":\"${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/cirrinaweb-linux-arm64\"}"
    - echo
