linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - gocyclo
    - asciicheck
    - decorder
    - dogsled
    - errname
    - forbidigo
    - unparam
    - sloglint
    - tagalign
    - gofmt
    - gci

issues:
  exclude-rules:
    - path: 'cirrinactl/rpc/vm_com.go'
      linters:
        - forbidigo
    - path: 'cirrinactl/cmd/.*.go'
      linters:
        - forbidigo

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(cirrina)
    custom-order: true
