linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - gocyclo
    - asciicheck
    - decorder
    - dogsled
    - errname
    - forbidigo
    - unparam
    - sloglint
    - tagalign
    - gofmt
    - gci
    - bodyclose
    - noctx
    - perfsprint
    - execinquery
    - rowserrcheck
    - sqlclosecheck
    - nestif
    - maintidx
    - gocognit
    - cyclop
    - errorlint
    - testifylint
    - zerologlint
    - dupword
    - misspell

issues:
  exclude-rules:
    - path: 'cirrinactl/rpc/vm_com.go'
      linters:
        - forbidigo
    - path: 'cirrinactl/cmd/.*.go'
      linters:
        - forbidigo
    - path: 'cirrinad/db/migrate.go'
      linters:
        - nestif
        - gocognit

linters-settings:
  cyclop:
    max-complexity: 16
  gci:
    sections:
      - standard
      - default
      - prefix(cirrina)
    custom-order: true
