linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - goimports
    - gocritic
    - gocyclo
    - asciicheck
    - decorder
    - dogsled
    - errname
