---
repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-build
      - id: golangci-lint
      - id: go-fmt
      - id: go-mod-tidy
      - id: go-imports
        exclude: |
            (?x)^(
                cirrina/cirrina_grpc.pb.go|
                cirrina/cirrina.pb.go
            )$
#      - id: go-cyclo
#        args: [-over=15]
#      - id: go-critic
