{
 "title": "Cirrina",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(cirrinad_VMs_defined,job)"
    }
   },
   {
    "name": "code",
    "query": {
     "query": "label_values(http_request_duration_seconds_count,code)"
    }
   },
   {
    "name": "method",
    "label": "Method",
    "query": {
     "query": "label_values(http_request_duration_seconds_count,method)"
    }
   },
   {
    "name": "handler",
    "label": "Handler",
    "query": {
     "query": "label_values(http_request_duration_seconds_count,handler)"
    }
   }
  ]
 },
 "panels": [
  { "title": "VMs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "VMs Defined",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "cirrinad_VMs_defined{job=\"$job\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "VMs Running",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "cirrinad_VMs_running{job=\"$job\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory Allocated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "cirrinad_VMs_Mem{job=\"$job\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "CPUs Allocated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "cirrinad_VMs_CPU{job=\"$job\"}",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count{job=~\"$job\", code=~\"$code\", method=~\"$method\", handler=~\"$handler\"}[$__rate_interval])",
     "legendFormat": "{{handler}} ({{method}} - {{code}})"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (irate(http_request_duration_seconds_bucket{job=~\"$job\", method=~\"$method\", handler=~\"$handler\"}[$__rate_interval]))) * 1",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (irate(http_request_duration_seconds_bucket{job=~\"$job\", method=~\"$method\", handler=~\"$handler\"}[$__rate_interval]))) * 1",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "(sum(irate(http_request_duration_seconds_sum{job=~\"$job\", method=~\"$method\", handler=~\"$handler\"}[$__rate_interval])) * 1) / sum(irate(http_request_duration_seconds_count{job=~\"$job\", method=~\"$method\", handler=~\"$handler\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  { "title": "VNC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "go_websockify_tcp_connections_active{job=\"$job\"}",
     "legendFormat": "TCP"
    },
    {
     "expr": "go_websockify_websocket_connections_active{job=\"$job\"}",
     "legendFormat": "WebSocket"
    }
   ]
  },
  {
   "title": "Network Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(go_websockify_websocket_bytes_rx_total{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Received"
    },
    {
     "expr": "rate(go_websockify_websocket_bytes_tx_total{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Transmitted"
    }
   ]
  }
 ]
}