// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: cirrina.proto

package cirrina

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VM struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Cpu         int32  `protobuf:"varint,4,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Mem         int32  `protobuf:"varint,5,opt,name=mem,proto3" json:"mem,omitempty"`
}

func (x *VM) Reset() {
	*x = VM{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cirrina_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VM) ProtoMessage() {}

func (x *VM) ProtoReflect() protoreflect.Message {
	mi := &file_cirrina_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VM.ProtoReflect.Descriptor instead.
func (*VM) Descriptor() ([]byte, []int) {
	return file_cirrina_proto_rawDescGZIP(), []int{0}
}

func (x *VM) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VM) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VM) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *VM) GetCpu() int32 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *VM) GetMem() int32 {
	if x != nil {
		return x.Mem
	}
	return 0
}

type VmID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *VmID) Reset() {
	*x = VmID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cirrina_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VmID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmID) ProtoMessage() {}

func (x *VmID) ProtoReflect() protoreflect.Message {
	mi := &file_cirrina_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmID.ProtoReflect.Descriptor instead.
func (*VmID) Descriptor() ([]byte, []int) {
	return file_cirrina_proto_rawDescGZIP(), []int{1}
}

func (x *VmID) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type VMsQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VMsQuery) Reset() {
	*x = VMsQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cirrina_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VMsQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMsQuery) ProtoMessage() {}

func (x *VMsQuery) ProtoReflect() protoreflect.Message {
	mi := &file_cirrina_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMsQuery.ProtoReflect.Descriptor instead.
func (*VMsQuery) Descriptor() ([]byte, []int) {
	return file_cirrina_proto_rawDescGZIP(), []int{2}
}

var File_cirrina_proto protoreflect.FileDescriptor

var file_cirrina_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x63, 0x69, 0x72, 0x72, 0x69, 0x6e, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x63, 0x69, 0x72, 0x72, 0x69, 0x6e, 0x61, 0x22, 0x6e, 0x0a, 0x02, 0x56, 0x4d, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x70, 0x75, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x63, 0x70, 0x75, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x65, 0x6d, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x6d, 0x65, 0x6d, 0x22, 0x1c, 0x0a, 0x04, 0x56, 0x6d, 0x49, 0x44,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x0a, 0x0a, 0x08, 0x56, 0x4d, 0x73, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x32, 0x7e, 0x0a, 0x06, 0x56, 0x4d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x23, 0x0a, 0x05,
	0x41, 0x64, 0x64, 0x56, 0x4d, 0x12, 0x0b, 0x2e, 0x63, 0x69, 0x72, 0x72, 0x69, 0x6e, 0x61, 0x2e,
	0x56, 0x4d, 0x1a, 0x0d, 0x2e, 0x63, 0x69, 0x72, 0x72, 0x69, 0x6e, 0x61, 0x2e, 0x56, 0x6d, 0x49,
	0x44, 0x12, 0x23, 0x0a, 0x05, 0x47, 0x65, 0x74, 0x56, 0x4d, 0x12, 0x0d, 0x2e, 0x63, 0x69, 0x72,
	0x72, 0x69, 0x6e, 0x61, 0x2e, 0x56, 0x6d, 0x49, 0x44, 0x1a, 0x0b, 0x2e, 0x63, 0x69, 0x72, 0x72,
	0x69, 0x6e, 0x61, 0x2e, 0x56, 0x4d, 0x12, 0x2a, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x56, 0x4d, 0x73,
	0x12, 0x11, 0x2e, 0x63, 0x69, 0x72, 0x72, 0x69, 0x6e, 0x61, 0x2e, 0x56, 0x4d, 0x73, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x1a, 0x0b, 0x2e, 0x63, 0x69, 0x72, 0x72, 0x69, 0x6e, 0x61, 0x2e, 0x56, 0x4d,
	0x30, 0x01, 0x42, 0x20, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x6d, 0x6f, 0x75,
	0x66, 0x2e, 0x6e, 0x65, 0x74, 0x2f, 0x73, 0x77, 0x69, 0x6c, 0x6c, 0x73, 0x2f, 0x63, 0x69, 0x72,
	0x72, 0x69, 0x6e, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cirrina_proto_rawDescOnce sync.Once
	file_cirrina_proto_rawDescData = file_cirrina_proto_rawDesc
)

func file_cirrina_proto_rawDescGZIP() []byte {
	file_cirrina_proto_rawDescOnce.Do(func() {
		file_cirrina_proto_rawDescData = protoimpl.X.CompressGZIP(file_cirrina_proto_rawDescData)
	})
	return file_cirrina_proto_rawDescData
}

var file_cirrina_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cirrina_proto_goTypes = []interface{}{
	(*VM)(nil),       // 0: cirrina.VM
	(*VmID)(nil),     // 1: cirrina.VmID
	(*VMsQuery)(nil), // 2: cirrina.VMsQuery
}
var file_cirrina_proto_depIdxs = []int32{
	0, // 0: cirrina.VMInfo.AddVM:input_type -> cirrina.VM
	1, // 1: cirrina.VMInfo.GetVM:input_type -> cirrina.VmID
	2, // 2: cirrina.VMInfo.GetVMs:input_type -> cirrina.VMsQuery
	1, // 3: cirrina.VMInfo.AddVM:output_type -> cirrina.VmID
	0, // 4: cirrina.VMInfo.GetVM:output_type -> cirrina.VM
	0, // 5: cirrina.VMInfo.GetVMs:output_type -> cirrina.VM
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cirrina_proto_init() }
func file_cirrina_proto_init() {
	if File_cirrina_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cirrina_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VM); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cirrina_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VmID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cirrina_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VMsQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cirrina_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cirrina_proto_goTypes,
		DependencyIndexes: file_cirrina_proto_depIdxs,
		MessageInfos:      file_cirrina_proto_msgTypes,
	}.Build()
	File_cirrina_proto = out.File
	file_cirrina_proto_rawDesc = nil
	file_cirrina_proto_goTypes = nil
	file_cirrina_proto_depIdxs = nil
}
